name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -e .[dev]

    - name: Get version from drydock/__about__.py
      id: get_version
      run: |
        VERSION=$(grep -Po '(?<=__version__ = ")[^"]*' drydock/__about__.py)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Create Git tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag v${{ steps.get_version.outputs.version }}
        git push origin v${{ steps.get_version.outputs.version }}

    - name: Build package
      run: |
        python -m build --sdist --wheel --outdir dist/ .

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
