name: Release PR (bump & changelog)

on:
  push:
    branches:
      - main

jobs:
  release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: python
